version: "3.8"

services:
  postgres_user:
    container_name: postgres_user
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_userservice
    volumes:
      - user_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres_message:
    container_name: postgres_message
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_messageservice
    volumes:
      - message_data:/var/lib/postgresql/data
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./my-app/build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - apigateway
  apigateway:
    build:
      context: ./src/gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - user-service
  user-service:
    build:
      context: ./src/user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres_user
  # --- Zookeeper cho Kafka ---
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  # --- Kafka ---
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  user_data:
  message_data:
