global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "message-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "kong"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["kong:8001"] # hoặc dùng host.docker.internal nếu Prometheus chạy ngoài Docker
