server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5     # số request/giây
                redis-rate-limiter.burstCapacity: 10    # tối đa khi tăng đột biến
  data:
    redis:
      host: localhost
      port: 6379
