name: Test Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      # Bước 3: Cache thư mục Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # Bước 4: Compile và chạy kiểm thử
    #   - name: Build and Test
    #     run: mvn -f wee-chat/gateway-service/pom.xml clean verify -Dspring.profiles.active=ci

    #   - name: Build and Test
    #     run: mvn -f wee-chat/user-service/pom.xml clean verify -Dspring.profiles.active=ci

    #   - name: Build and Test
    #     run: mvn -f wee-chat/message-service/pom.xml clean verify -Dspring.profiles.active=ci
