name: CI Workflow

on:
  push:
    branches:
      - main
      - master
      - docker-kafka-config
      - setup-fe
      - storage
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      # - name: Bring up services
      #   run: docker-compose -f docker-compose.yml up -d
      # - name: Wait for Kafka to be ready
      #   run: |
      #     until docker exec kafka kafka-topics --list --bootstrap-server localhost:9092; do
      #       echo "Waiting for Kafka to be ready..."
      #       sleep 5
      #     done
      # - name: Run Tests
      #   run: |
      #     # Run your tests here, assuming Kafka is ready
      #     docker-compose exec app ./run-tests.sh
