name: CI Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_sweetchat
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and test the app
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose exec sweetchat-backend mvn test
          docker-compose exec sweetchat-frontend npm test
