name: Test Frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: false
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: my-app/package-lock.json

      # Cài đặt dependencies
      - name: Install dependencies
        run: npm install
        working-directory: my-app

      # Xây dựng dự án
      - name: Run build
        run: npm run build
        working-directory: my-app

      # Kiểm tra kết quả build
      - name: Verify build
        run: ls -la my-app/dist
